default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:
  password:

development:
  <<: *default
  database: beproductive360_development

test:
  <<: *default
  database: beproductive360_test

production:
  <<: *default
  database: beproductive360_production
